name: Automated Daily Commits

# Schedule the workflow to run at a specific time every day (e.g., 00:00 UTC)
on:
  schedule:
    - cron: '0 0 * * *'  # This will run every day at midnight UTC
  workflow_dispatch:  # You can still manually trigger the workflow

jobs:
  commit-loop:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Configure Git with GitHub Actions bot username and email
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Commit 3 times (loop 3 times)
      - name: Commit 3 times a day
        run: |
          for i in {1..3}; do  # Loop 3 times, once per commit
            echo "Test commit #$i at $(date)" >> test_commit.txt
            git add .
            git commit -m "Automated test commit #$i - $(date)" || echo "No changes to commit"
            git push https://x-access-token:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}.git
            echo "Commit #$i pushed at $(date)"
            sleep 8h  # Wait for 8 hours before the next commit
          done
