name: Test Rapid Commits

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  commit-loop:
    runs-on: ubuntu-latest  # Use a Ubuntu environment for the job

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Configure Git with your username and email
      - name: Configure Git
        run: |
          git config --global user.name "sharan-dev-ae"
          git config --global user.email "sharan.devae@gmail.com"

      # Step 3: Loop to make commits every 10 seconds
      - name: Commit every 10 seconds
        run: |
          for i in {1..10}; do  # Loop 10 times, 100 seconds in total
            echo "Test commit at $(date)" >> test_commit.txt  # Modify file to make a commit
            git add .
            git commit -m "Automated test commit - $(date)" || echo "No changes to commit"
            git push
            echo "Commit #$i pushed at $(date)"
            sleep 10  # Wait for 10 seconds before next commit
          done
